### ISSUE TITLE
[feature-request] Add webp polyfill

### ISSUE THREAD

**Issue by develerik** [Financial-Times/polyfill-service#1989]
## What
It would be cool if you could include a webp polyfill in your service (maybe [webp-hero](https://github.com/chase-moskal/webp-hero)).

## Details
I regularly use WebP to reduce my file size, but I also have to support IE11 which does not support this format. And because I really like your service and use it for other polyfills too it would be great if you could integrate one for WebP.

## Additional information

> WebP is an image format employing both lossy and lossless compression. It is currently developed by Google, based on technology acquired with the purchase of On2 Technologies.

**Comment by sjparkinson** [comment]
> Browser polyfill for the webp image format.
> 
> * webp images come alive, even in safari and ie11! (firefox and edge now support webp)
> * webp-hero actually runs google's `libwebp` decoder in the browser — it converts webp images to png's on-the-fly
> * webp-hero's polyfill functionality renders decoded image data to a hidden canvas, and converts that to a png data url which is then displayed to the user

https://github.com/chase-moskal/webp-hero

**Comment by JakeChampion** [comment]
Hi, I don't think we will add a polyfill for webp, it is a very large polyfill and only works in some scenarios (does not work for webp images used in CSS). I would recommend using the srcset attribute on an IMG tag and serving PNG or jpeg to browsers which don't have webp support
