### ISSUE TITLE
Object.freeze

### ISSUE THREAD

**Issue by zordius** [Financial-Times/polyfill-service#232]
Can we apply Object.freeze() polyfill here but it works as silent failed?

**Comment by blainekasten** [comment]
Could these exist under a specific flag? I feel like in development mode I would want to be alerted of this. But I could see an argument for supressing errors in production mode in hopes that the app will have more functionality than simply kill js execution due to a method erroring.

**Comment by vvo** [comment]
I am going to include `Object.freeze = identity` (return obj) for browsers not supporting it because my app needs it, happy to submit a PR here where it would not be activated by default but only on demand.

Wonder if that works for you, I guess no :)

**Comment by triblondon** [comment]
We do now have a few examples of 'cheat' polyfills... notably the devicePixelRatio polyfill that simply returns `1` on the basis that any device that doesn't support it is likely to have a standard density display.  However, I'm still very wary of going near APIs where we can't even simulate the behaviour. I think the most I'd consider doing here is implementing a method that does `console.warn('Not implemented (polyfill.io)')` or similar, just to prevent an unhandled exception causing a break in your runtime code.

**Comment by vvo** [comment]
So still implementing it but without even taking the es5-sham, just warning to have the good error message for the users?

Or do you want to implement it + do a console.warn?

> just to prevent an unhandled exception causing a break in your runtime code.

It will still break if we do not return the object I guess
